{
 "title": "MongoDB Overview (Telegraf)",
 "tags": [
  "mongo",
  "telegraf"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "MongoDB Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "targets": [
    { "expr": "mongodb_connections_current", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Ops per second (insert)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "targets": [
    { "expr": "rate(mongodb_insert_total[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Ops per second (query)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "targets": [
    { "expr": "rate(mongodb_query_total[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Document operations (per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "expr": "rate(mongodb_insert_total[5m])", "legendFormat": "insert" },
    { "expr": "rate(mongodb_update_total[5m])", "legendFormat": "update" },
    { "expr": "rate(mongodb_delete_total[5m])", "legendFormat": "delete" }
   ]
  }
 ]
}