export const routes = {
  users: {
    path: '/admin/users',
    name: 'Users',
    tKey: 'navigation.users' as const,
    needAuth: true,
  },
  home: {
    path: '/',
    name: 'Home',
    tKey: 'navigation.home' as const,
    needAuth: false,
  },
  uiKit: {
    path: '/ui-kit',
    name: 'UI Kit',
    tKey: 'navigation.uiKit' as const,
    needAuth: false,
  },
  profile: {
    path: '/profile',
    name: 'Profile',
    tKey: 'navigation.profile' as const,
    needAuth: true,
  },
  login: {
    path: '/login',
    name: 'Login',
    tKey: 'navigation.login' as const,
    needAuth: false,
  },
  logout: {
    path: '/logout',
    name: 'Logout',
    tKey: 'navigation.logout' as const,
    needAuth: false,
  },
  refresh: {
    path: '/refresh',
    name: 'Refresh',
    tKey: 'navigation.refresh' as const,
    needAuth: false,
  },
  rumDashboard: {
    path: '/admin/rum',
    name: 'RUM',
    tKey: 'navigation.rumDashboard' as const,
    needAuth: true,
  },
  articleViewsDashboard: {
    path: '/admin/article-views',
    name: 'Article views',
    tKey: 'navigation.articleViewsDashboard' as const,
    needAuth: true,
  },
  aiReferralsDashboard: {
    path: '/admin/ai-referrals',
    name: 'AI Referrals',
    tKey: 'navigation.aiReferralsDashboard' as const,
    needAuth: true,
  },
  llmUsageDashboard: {
    path: '/admin/llm-usage',
    name: 'LLM usage',
    tKey: 'navigation.llmUsageDashboard' as const,
    needAuth: true,
  },
  i18nDashboard: {
    path: '/admin/i18n',
    name: 'I18n',
    tKey: 'navigation.i18nDashboard' as const,
    needAuth: true,
  },
  articles: {
    path: '/admin/articles',
    name: 'Articles',
    tKey: 'navigation.articles' as const,
    needAuth: true,
  },
  articlesCreate: {
    path: '/admin/articles/create',
    name: 'Create Article',
    tKey: 'navigation.articlesCreate' as const,
    needAuth: true,
  },
  articlePublic: {
    path: '/article/:slug',
    name: 'Article',
    tKey: 'navigation.articlePublic' as const,
    needAuth: false,
  },
  articlesPublic: {
    path: '/articles',
    name: 'Articles',
    tKey: 'navigation.articlesPublic' as const,
    needAuth: false,
  },
  articlePreview: {
    path: '/preview/:slug',
    name: 'Article Preview',
    tKey: 'navigation.articlePreview' as const,
    needAuth: true,
  },
  articlePrivate: {
    path: '/private-article/:slug',
    name: 'Article Private',
    tKey: 'navigation.articlePrivate' as const,
    needAuth: true,
  },
}
