[[inputs.nginx]]
  urls = ["http://nginx-container/nginx_status"]
  response_timeout = "5s"

[[inputs.cpu]]
  percpu = true

[[inputs.disk]]

[[inputs.diskio]]

[[inputs.net]]
  # Remove deprecated param
  # ignore_protocol_stats = false

[[inputs.mem]]

[[inputs.system]]

[[inputs.mongodb]]
  ## MongoDB connection URI (auth user should have at least cluster monitor role)
  ## Values are passed via environment variables from docker-compose.local.yml.
  servers = ["mongodb://${MONGO_METRICS_USER}:${MONGO_METRICS_PASSWORD}@mongo:27017/admin"]
  gather_perdb_stats = true
  gather_col_stats = false
  gather_cluster_status = false
  gather_top_stat = false

# Prometheus output plugin

[[outputs.prometheus_client]]
  listen = ":9273"
