FROM nginx:latest

# Install necessary utilities
RUN apt-get update && apt-get install -y \
    net-tools \
    curl \
    gettext-base \
    && rm -rf /var/lib/apt/lists/*

RUN rm -f /etc/nginx/conf.d/default.conf
# Create directories
RUN mkdir -p /etc/nginx/templates
